# Generated by Django 3.0.6 on 2023-09-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('area1', models.CharField(blank=True, max_length=255, null=True)),
                ('area2', models.CharField(blank=True, max_length=255, null=True)),
                ('locality', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('href', models.URLField()),
            ],
        ),
    ]
